services:
  db:
    image: postgres:14
    container_name: wishlist_db
    restart: always
    environment:
      POSTGRES_DB: wishlist
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


  web:
    build: .
    container_name: wishlist_web
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - POSTGRES_DB =  wishlist
      - POSTGRES_USER = user
      - POSTGRES_PASSWORD = password
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    command: [ "sh", "entrypoint.sh" ]

volumes:
  postgres_data: