name: Django CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python (for linting only)
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install tools for linting
      working-directory: wishlist
      run: |
        python -m pip install --upgrade pip
        pip install black isort

    - name: Lint & check formatting
      working-directory: wishlist
      run: |
        black . --check
        isort . --check-only

    - name: Build Docker image
      working-directory: wishlist
      run: docker compose -f docker-compose.yml build

    - name: Run migrations and tests inside container
      working-directory: wishlist
      run: |
        docker compose -f docker-compose.yml run --rm web sh -c "
          python manage.py migrate &&
          pytest -v
        "
