name: Django CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: |
        docker compose -f wishlist/docker-compose.yml build

    - name: Run migrations and tests inside container
      run: |
        docker compose -f wishlist/docker-compose.yml run --rm web sh -c "
          python wishlist/manage.py migrate &&
          pytest -v
        "

    - name: Check formatting and lint
      run: |
        pip install black isort
        black . --check
        isort . --check-only
